# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"
evm_version = "cancun"
# optimizer_runs = 44444444
# via_ir = true
# ffi = true
# fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}, { access = "read", path = "./out"}, {access = "read", path = "./test/bin"}]
# solc = "0.8.26"
# gas_limit = "300000000"
# bytecode_hash = "none"
# allow_internal_expect_revert = true

[profile.debug]
via_ir = false
optimizer_runs = 200
fuzz.runs = 100

# [profile.default.fuzz]
# runs = 1000
# seed = "0x4444"
# [profile.pr.fuzz]
# runs = 10000
# [profile.ci.fuzz]
# runs = 100000
